# Define the building environment
os: linux
dist: bionic
language: c

git:
  depth: 3


env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "TODO"


addons:
  apt:
    packages:
      - bison
      - flex
      - gawk
      - gettext
      - libaudit-dev
      - libbz2-dev
      - libcap-dev
      - libcap-ng-dev # This package is not whitelisted for the container infrastructure (https://github.com/travis-ci/apt-package-whitelist/issues/1096)
      - libcunit1-dev
      - libglib2.0-dev
      - libpcre3-dev
      - patch
      - python3-dev
      - python-dev
      - swig
      - xmlto
  coverity_scan:
    project:
      name: "SELinuxProject/selinux"
      description: "Build submitted via Travis CI"
    notification_email: selinux@vger.kernel.org
    build_command_prepend: "make clean"
    build_command: "export DESTDIR=$TRAVIS_BUILD_DIR/installdir && make install && make all"
    branch_pattern: coverity_scan


script:
  - cat "${TRAVIS_BUILD_DIR}/cov-int/scm_log.txt"
